### ISSUE TITLE
A suggestion btw: How about creating cfg rules to generate lines ?

### ISSUE THREAD

**Issue by sktguha** [Kovah/DevLorem#1]

**Comment by Kovah** [comment]
What do you mean with cfg rules?

**Comment by sktguha** [comment]
I mean context free grammar rules
<code>
var store = {
"full" : "<adj> <hero> <verb> <vadj> <villain> | hulk smash little <villain> | <hero> is <adj> | <villain> is <vadj> ",
"hero" : "batman | superman | spiderman | ironman | thor", 
"villain" : "doom | darkseid | joker | loki | thanos",
"verb" : "hits | kicks | punches | hits",
"adj" : "quick | nimble | strong | smart",
"vadj" : "stupid | cunning | evil | mad"
};
</code>
For example. https://github.com/sktguha/computer-science-in-javascript/blob/master/algorithms/context_free_grammer_test.js

**Comment by Kovah** [comment]
Why should I use them? This generator is about quotes from real people.
